### ISSUE TITLE
README has strange instructions

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-app-pgb#1]
If you follow the instructions under 

> To build this yourself, clone the repo and initialize with npm:

You will see npm warnings because there is not a package.json file 

```
🚀 npm install
npm WARN ENOENT ENOENT: no such file or directory, open '/Repos/phonegap-app-pgb/package.json'
```

It is unclear if there _should_ be a package.json or not, so I cannot simply send a pr without knowing.

**Comment by wildabeast** [comment]
`npm install` unneeded, readme updated, :beers:
