### ISSUE TITLE
Android install support

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-pgb#10]
Can we install an app onto an Android device using the Install button?

_(I think the answer is yes)_

**Comment by wildabeast** [comment]
Yes

**Comment by infil00p** [comment]
You have to be able to check "Unknown Sources" setting for this to work the same way.  This is found in Security on Android N.  Otherwise, this won't work and you will only download the APK, not install it.

**Comment by mwbrooks** [comment]
@infil00p awesome, thanks! This is important and we would have forgot about it.
