### ISSUE TITLE
No scroll inertia/momentum 

### ISSUE THREAD

**Issue by edvenkat** [phonegap/phonegap-app-pgb#14]
Hai All,

No scroll inertia/momentum - when i scroll the page, the event scroll call only end of the scroll not between

please advice

```
$$('#xxx').scroll(function () {
}); 
```

**Comment by wildabeast** [comment]
Don't think this has anything to do with the phonegap-app-pgb project... is this an issue you're having with your own PhoneGap app?

Maybe take it to the [PhoneGap support forum](forums.adobe.com/community/phonegap).
