### ISSUE TITLE
Authorize Account: Yes / No buttons are too small

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap-app-pgb#4]
Fat fingered people will clumsily touch "No" and have to login all over again.

Screenshot:
<img src="https://cloud.githubusercontent.com/assets/36107/18654525/bb8af9b8-7e96-11e6-9f28-c079f6d7d97b.PNG" width=350 />

**Comment by wildabeast** [comment]
<img src="https://upload.wikimedia.org/wikipedia/en/5/55/King-Size_Homer.png" width=500 />

**Comment by wildabeast** [comment]
Fixed on build, will be deployed soon.
